version: '3.8'

services:
  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:4000"]  # Adjust health check URL and command
      interval: 30s   # Check health every 30 seconds
      timeout: 5s    # Timeout for each health check attempt
      retries: 3      # Number of retries before considering the container unhealthy
    environment:
      - JWT_SECRET=qwdwqwqdwqdqwd
      - STRIPE_SECRET_KEY=sk_test_51PRDWY1C56reqfLSPoLDuTI8T7npwnnqmFqU3M1Iqqq89UqcKA4mHxAH0L5010rZbXzYf6SEf2xhBjnwHhxaJqft00Gu4plg5y
      - RETURN_URL=http://localhost:3000/home
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
      - DATABASE_NAME=ecommerce
      - API_BASE_URL=http://localhost:3000
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    command: ["--bind-address=0.0.0.0"]
  web: 
    build: 
      context: ./packages/web
      dockerfile: Dockerfile
    environment:
      - VITE_BACKEND_URL=http://localhost:4000
      - VITE_API_BASE_URL=http://server:4000
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    ports:
      - "3000:3000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: host.docker.internal
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
volumes:
  mysql-data: