services:
  - type: web
    name: frontend-web
    env: docker
    dockerfilePath: ./packages/web/Dockerfile
    envVars:
      - key: VITE_BACKEND_URL
        value: http://localhost:4000
      - key: VITE_API_BASE_URL
        value: http://backend-server:4000
    buildCommand: npm run build