services:
  - type: web
    name: server
    env: docker
    dockerfilePath: ./packages/server/Dockerfile
    buildContext: ./packages/server
    port: 4000
    envVars:
      - key: JWT_SECRET
        value: qwdwqwqdwqdqwd
      - key: STRIPE_SECRET_KEY
        value: sk_test_51PRDWY1C56reqfLSPoLDuTI8T7npwnnqmFqU3M1Iqqq89UqcKA4mHxAH0L5010rZbXzYf6SEf2xhBjnwHhxaJqft00Gu4plg5y
      - key: RETURN_URL
        value: http://localhost:3000/home
      - key: DATABASE_HOST
        value: mysql-db
      - key: DATABASE_PORT
        value: "3306"
      - key: DATABASE_USER
        value: root
      - key: DATABASE_PASSWORD
        value: ""
      - key: DATABASE_NAME
        value: ecommerce1
      - key: API_BASE_URL
        value: http://localhost:3000
    healthCheckPath: /health
    startCommand: ["npm", "start"]
    dependencies:
      - name: mysql-db
